"""
rfm.py — RFM Feature Engineering
===================================
Recency, Frequency, and Monetary Value are the three cornerstone metrics
in customer analytics. Every downstream model benefits from these features.
"""

import logging
import pandas as pd

from src.config import CHURN_THRESHOLD_DAYS

logger = logging.getLogger(__name__)


def compute_rfm(customer_base: pd.DataFrame) -> pd.DataFrame:
    """
    Compute RFM features on a customer-level base dataframe.

    Features created:
        recency_days   : Days since last purchase (relative to dataset max date)
        frequency      : Total number of orders placed
        monetary_value : Total revenue generated by the customer

    Returns:
        DataFrame with rfm columns added (does not modify input in-place).
    """
    df = customer_base.copy()

    # Reference date = latest purchase in the dataset (no future leakage)
    reference_date: pd.Timestamp = df["last_purchase_date"].max()
    logger.info(f"RFM reference date (dataset max): {reference_date.date()}")

    # Recency: days since last purchase
    df["recency_days"] = (
        reference_date - df["last_purchase_date"]
    ).dt.total_seconds() / 86400
    df["recency_days"] = df["recency_days"].round(0).astype(int)

    # Frequency: total distinct orders
    df["frequency"] = df["total_orders"].fillna(1).astype(int)

    # Monetary Value: total payment value across all orders
    df["monetary_value"] = df["total_revenue"].fillna(0).round(2)

    logger.info(
        f"RFM computed for {len(df):,} customers | "
        f"Recency range: {df['recency_days'].min()}–{df['recency_days'].max()} days"
    )
    return df
